bullet/bullet/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

bullet/bullet_admin/urls.py
from bullet_admin.views import (
    CompetitionSwitchView,
    albums,
    archive,
    auth,
    category,
    categoryproblems,
    competition,
    content,
    documents,
    education,
    emails,
    home,
    results,
    scanning,
    teams,
    users,
    venues,
)
from django.urls import path

app_name = "badmin"
urlpatterns = [
    path("", home.HomeView.as_view(), name="home"),
    path("release_notes/", home.ReleaseNotesView.as_view(), name="release_notes"),
    path("auth/login/", auth.LoginView.as_view(), name="login"),
    path("auth/logout/", auth.LogoutView.as_view(), name="logout"),
    path(
        "auth/password_change/",
        auth.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "auth/password_reset/",
        auth.PasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "auth/password_reset/<uidb64>/<token>/",
        auth.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path("competitions/", CompetitionSwitchView.as_view(), name="competition_switch"),
    path(
        "competitions/edit/",
        competition.CompetitionUpdateView.as_view(),
        name="competition_edit",
    ),
    path(
        "competitions/new/",
        competition.CompetitionCreateView.as_view(),
        name="competition_create",
    ),
    path(
        "competitions/finalize/",
        competition.CompetitionFinalizeView.as_view(),
        name="competition_finalize",
    ),
    path("categories/", category.CategoryListView.as_view(), name="category_list"),
    path(
        "categories/new", category.CategoryCreateView.as_view(), name="category_create"
    ),
    path(
        "categories/<pk>", category.CategoryUpdateView.as_view(), name="category_edit"
    ),
    path("content/pages/", content.PageListView.as_view(), name="page_list"),
    path("content/pages/new/", content.PageCreateView.as_view(), name="page_create"),
    path("content/pages/<pk>/", content.PageEditView.as_view(), name="page_edit"),
    path(
        "content/pages/<pk>/delete/",
        content.PageDeleteView.as_view(),
        name="page_delete",
    ),
    path(
        "content/blocks/",
        content.ContentBlockListView.as_view(),
        name="contentblock_list",
    ),
    path(
        "content/blocks/trans/<group>/<reference>/",
        content.ContentBlockTranslationListView.as_view(),
        name="contentblock_trans",
    ),
    path(
        "content/blocks/new/",
        content.ContentBlockCreateView.as_view(),
        name="contentblock_create",
    ),
    path(
        "content/blocks/edit/<pk>/",
        content.ContentBlockEditView.as_view(),
        name="contentblock_edit",
    ),
    path(
        "content/blocks/delete/<pk>/",
        content.ContentBlockDeleteView.as_view(),
        name="contentblock_delete",
    ),
    path(
        "content/logos/",
        content.LogoListView.as_view(),
        name="logo_list",
    ),
    path(
        "content/logos/edit/<pk>/",
        content.LogoEditView.as_view(),
        name="logo_edit",
    ),
    path(
        "content/logos/create/",
        content.LogoCreateView.as_view(),
        name="logo_create",
    ),
    path(
        "content/logos/delete/<pk>/",
        content.LogoDeleteView.as_view(),
        name="logo_delete",
    ),
    path(
        "content/menu/",
        content.MenuItemListView.as_view(),
        name="menu_list",
    ),
    path(
        "content/menu/edit/<pk>/",
        content.MenuItemEditView.as_view(),
        name="menu_edit",
    ),
    path(
        "content/menu/delete/<pk>/",
        content.MenuItemDeleteView.as_view(),
        name="menu_delete",
    ),
    path(
        "content/menu/create/",
        content.MenuItemCreateView.as_view(),
        name="menu_create",
    ),
    path("teams/", teams.TeamListView.as_view(), name="team_list"),
    path(
        "teams/assign_numbers/",
        teams.AssignTeamNumbersView.as_view(),
        name="team_assign_numbers",
    ),
    path("teams/export/", teams.TeamExportView.as_view(), name="team_export"),
    path("teams/<int:pk>/", teams.TeamEditView.as_view(), name="team_edit"),
    path(
        "teams/<int:pk>/to_competition/",
        teams.TeamToCompetitionView.as_view(),
        name="team_to_competition",
    ),
    path(
        "teams/<int:pk>/resend_confirmation/",
        teams.TeamResendConfirmationView.as_view(),
        name="team_resend_confirmation",
    ),
    path(
        "teams/<int:pk>/delete/",
        teams.TeamDeleteView.as_view(),
        name="team_delete",
    ),
    path("teams/waiting/", teams.WaitingListView.as_view(), name="waiting_list"),
    path(
        "teams/waiting/automove/",
        teams.WaitingAutomoveView.as_view(),
        name="waiting_automove",
    ),
    path("_school_input", teams.SchoolInputView.as_view(), name="school_input"),
    path("users/", users.UserListView.as_view(), name="user_list"),
    path("users/create/", users.UserCreateView.as_view(), name="user_create"),
    path("users/<int:pk>/", users.UserEditView.as_view(), name="user_edit"),
    path(
        "scanning/problems/",
        scanning.ProblemScanView.as_view(),
        name="scanning_problems",
    ),
    path(
        "scanning/problems/undo/",
        scanning.UndoScanView.as_view(),
        name="scanning_problems_undo",
    ),
    path(
        "scanning/review/",
        scanning.VenueReviewView.as_view(),
        name="scanning_review",
    ),
    path(
        "scanning/review/<int:pk>/",
        scanning.TeamReviewView.as_view(),
        name="scanning_review_team",
    ),
    path(
        "scanning/review/<int:pk>/toggle/",
        scanning.TeamToggleReviewedView.as_view(),
        name="scanning_review_toggle_team",
    ),
    path("scanning/problems/api/", scanning.ApiProblemSolveView.as_view()),
    path("emails/", emails.CampaignListView.as_view(), name="email_list"),
    path("emails/create/", emails.CampaignCreateView.as_view(), name="email_create"),
    path(
        "emails/<int:pk>/edit/", emails.CampaignUpdateView.as_view(), name="email_edit"
    ),
    path("emails/<int:pk>/", emails.CampaignDetailView.as_view(), name="email_detail"),
    path(
        "emails/<int:pk>/teams/",
        emails.CampaignTeamListView.as_view(),
        name="email_teams",
    ),
    path(
        "emails/<int:pk>/test/",
        emails.CampaignSendTestView.as_view(),
        name="email_test",
    ),
    path(
        "emails/<int:pk>/send/",
        emails.CampaignSendView.as_view(),
        name="email_send",
    ),
    path(
        "documents/certificates/",
        documents.CertificateView.as_view(),
        name="docs_certificates",
    ),
    path(
        "documents/team_lists/",
        documents.TeamListView.as_view(),
        name="docs_teamlists",
    ),
    path("results/", results.ResultsHomeView.as_view(), name="results"),
    path(
        "results/announce/<venue>/",
        results.ResultsAnnouncementView.as_view(),
        name="results_announce",
    ),
    path("venues/", venues.VenueListView.as_view(), name="venue_list"),
    path("venues/<int:pk>/", venues.VenueUpdateView.as_view(), name="venue_update"),
    path("venues/create/", venues.VenueCreateView.as_view(), name="venue_create"),
    path("education/schools/", education.SchoolListView.as_view(), name="school_list"),
    path(
        "education/schools/<int:pk>/",
        education.SchoolUpdateView.as_view(),
        name="school_update",
    ),
    path(
        "education/schools/create/",
        education.SchoolCreateView.as_view(),
        name="school_create",
    ),
    path(
        "problems/generate/",
        categoryproblems.ProblemsGenerateView.as_view(),
        name="problems_generate",
    ),
    path("gallery/albums/", albums.AlbumListView.as_view(), name="album_list"),
    path("gallery/albums/new/", albums.AlbumCreateView.as_view(), name="album_create"),
    path(
        "gallery/albums/<int:pk>/", albums.AlbumUpdateView.as_view(), name="album_edit"
    ),
    path(
        "archive/import/",
        archive.ProblemImportView.as_view(),
        name="archive_import",
    ),
]

bullet/web/urls.py
from countries.views import CountryDetectView, CountrySelectView
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path, re_path

from web import views
from web.views import page

urlpatterns = [
    path("", CountryDetectView.as_view(), name="root"),
    path("country_selector/", CountrySelectView.as_view(), name="country_selector"),
    path("admin/", include("bullet_admin.urls")),
    re_path(
        r"^(?P<b_country>[a-z]{2})/(?P<b_language>[a-z\-]+)/",
        include(
            [
                path("", page.PageView.as_view(), name="homepage"),
                path("", include("competitions.urls")),
                path("", include("problems.urls")),
                path("", include("gallery.urls")),
                path("admin/", views.AdminRedirectView.as_view()),
                path("<slug>/", page.PageView.as_view(), name="page"),
            ]
        ),
    ),
]

handler404 = "web.views.error_404_view"

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns.append(
    re_path(
        r"^(?!([a-z]{2})/([a-z\-]+)/).*/", CountryDetectView.as_view(), name="redirect"
    )
)

bullet/web/templates/web/base.html
{% extends "web/root_base.html" %}
{% load bullet static %}
{% block root_content %}
    {% block main %}
        <div class="border-b-4 border-primary bg-gray-900">
            <div class="flex flex-wrap align-baseline gap-1 max-w-7xl mx-auto py-4 px-6 lg:px-8 justify-between">
                {% branch_selector %}
                <div class="flex items-center gap-4">
                    {% if user.is_authenticated %}
                        <a href="{% url "badmin:home" %}"
                           class="text-gray-500 hover:text-gray-300 text-lg">Admin</a>
                    {% endif %}
                    <a href="{% url "country_selector" %}"
                       class="text-gray-500 hover:text-gray-300 ms-auto text-right whitespace-nowrap flex items-center gap-2">
                        <b-icon icon="mdi:globe" class="size-5"></b-icon>
                        Change language
                    </a>
                </div>
            </div>
        </div>
        <header class="bg-hero">
            <div class="max-w-7xl mx-auto py-6 md:py-12 px-6 lg:px-8 {% block heroclass %} {% endblock %}">
                <div id="default-nav">
                    {% main_nav True %}
                </div>
                {% block hero %}
                {% endblock hero %}
            </div>
        </header>
        <div class="border-b-2 border-primary shadow-lg transition-transform fixed bg-white top-0 transform-gpu -translate-y-full w-full z-10"
             id="backup-nav">
            <div class="mx-auto max-w-7xl px-6 lg:px-8 py-4">
                {% main_nav %}
            </div>
        </div>
        {% block content %}
            {# Actual page content goes here #}
        {% endblock content %}
    {% endblock main %}
    {% block footer %}
        {% include "web/snippets/copyright.html" %}
    {% endblock footer %}
    <script type="text/javascript"
            src="{% static 'js/navbar.js' %}"></script>
    {% if not debug %}
        <script defer
                data-domain="{{ branch.domain }}"
                src="https://analytics.trojsten.sk/js/script.js"></script>
    {% endif %}
{% endblock root_content %}

bullet/web/templates/web/page.html
{% extends "web/base.html" %}
{% load markdownify page_blocks %}
{% block title %}
  {{ page.title }}
{% endblock title %}

{% block hero %}
  {% if not page_blocks %}
    <h1 class="text-4xl md:text-6xl font-bold mt-8 md:mt-24 mb-4 md:mb-16">
      {{ page.title }}
    </h1>
  {% endif %}
{% endblock hero %}

{% block content %}
  {% for page_block in page_blocks %}
    {% render_page_block page_block %}
  {% empty %}
    <main class="py-8 prose mx-auto max-w-7xl px-6 lg:px-8">
      {{ page.content|markdownify }}
    </main>
  {% endfor %}

  {% if page_blocks %}
    {% include "web/snippets/state_selector.html" %}
  {% endif %}
{% endblock content %}

bullet/web/templates/web/root_base.html
{% load i18n static %}
<!DOCTYPE html>{% get_current_language_bidi as lang_bidi %}
<html lang="{{ request.LANGUAGE_CODE }}"
      {% if lang_bidi %}dir="rtl"{% endif %}>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta name="description"
              content="{% block description %} {% endblock %}">
        <meta name="keywords"
              content="{% block keywords %} {{ branch.name }},Competition,STEM {% endblock %}">
        <meta http-equiv="X-UA-Compatible"
              content="ie=edge">
        <title>
            {% block title %}
            {% endblock title %}
        – {{ branch.name }}</title>
        <link rel="icon"
              type="image/svg+xml"
              href="{% static 'img/icon.svg' %}">
        <link rel="mask-icon"
              href="{% static 'img/icon.svg' %}"
              color="white">
        <link rel="preconnect"
              href="https://fonts.googleapis.com">
        <link rel="preconnect"
              href="https://fonts.gstatic.com"
              crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Work+Sans:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
        <link rel="stylesheet"
              href="{% static 'app.css' %}?v={{ bullet_version }}"
              type="text/css" />
        {% block extrahead %}
        {% endblock extrahead %}
        <script src="https://code.iconify.design/iconify-icon/3.0.0/iconify-icon.min.js"></script>
        <script>
            let originalIconifyIcon = window.customElements.get("iconify-icon");
            class CustomIconifyIcon extends originalIconifyIcon {
                constructor() {
                    super();
                    if (!this.hasAttribute("height") && !this.hasAttribute("width")) {
                        setTimeout(() => {
                            this.setAttribute("height", "none");
                            this.setAttribute("width", "none");
                        }, 0);
                    }
                }
            }
            window.customElements.define("b-icon", CustomIconifyIcon);
        </script>
        <link rel="stylesheet"
              href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
        <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    </head>
    <body class="branch-{{ branch.identifier }}"
          hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
        {% block root_content %}
        {% endblock root_content %}
        {% block messages %}
            {% if messages %}
                <ul class="fixed right-0 top-0 z-20 m-6 max-w-prose space-y-4">
                    {% for message in messages %}
                        <li class="border border-gray-200 p-4 rounded-sm relative bg-white shadow-xl flex items-center justify-between gap-3">
                            <div class="flex items-center gap-3">
                                <div class="shrink-0 flex items-center">
                                    {% if message.tags == "info" %}
                                        <b-icon icon="mdi:info" class="size-5 text-cyan-500"></b-icon>
                                    {% elif message.tags == "success" %}
                                        <b-icon icon="mdi:check-circle" class="size-5 text-green-600"></b-icon>
                                    {% elif message.tags == "warning" %}
                                        <b-icon icon="mdi:warning" class="size-5 text-amber-600"></b-icon>
                                    {% elif message.tags == "error" %}
                                        <b-icon icon="mdi:cross-circle" class="size-5 text-red-600"></b-icon>
                                    {% endif %}
                                </div>
                                <span>{{ message }}</span>
                            </div>
                            <div onclick="this.parentNode.remove()"
                                 class="shrink-0 text-gray-600 hover:text-gray-900 cursor-pointer"
                                 role="button"
                                 title="{% translate "Close" %}">
                                <b-icon icon="mdi:close" class="size-5"></b-icon>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        {% endblock messages %}
        <script src="https://unpkg.com/htmx.org@1.8.0"
                defer></script>
        <script>
        flatpickr(".datetime-picker", {
            enableTime: true,
            time_24hr: true,
        });

        flatpickr(".time-picker", {
            enableTime: true,
            noCalendar: true,
            time_24hr: true,
        });
        </script>
    </body>
</html>

bullet/web/templates/web/team_edit.html
{% extends "web/base.html" %}
{% load bform %}
{% load static %}
{% load i18n %}

{% block title %}Edit Team{% endblock %}
{% block hero %}
<h1 class="text-4xl md:text-6xl font-bold mt-8 md:mt-24 mb-4 md:mb-16">Edit Team</h1>
{% endblock %}

{% block content %}
    <main class="mx-auto w-full max-w-4xl p-3">

        <section class="py-5 my-5 border-b">
            <h2 class="text-3xl mb-3">Team Information</h2>

            <p>
                <strong>School:</strong>
                {{ team.school }}

                {% if team.in_school_symbol %}
                    <span class="text-white bg-primary py-0.5 px-2 rounded">{{ team.in_school_symbol }}</span>
                {% endif %}
            </p>
            <p><strong>Competition site:</strong> {{ team.competition_venue }}</p>
            <p><strong>Contact name:</strong> {{ team.contact_name }}</p>
            <p><strong>Contact email:</strong> {{ team.contact_email }}</p>
            {% if team.contact_phone %}
                <p><strong>Contact phone:</strong> {{ team.contact_phone }}</p>
            {% endif %}
        </section>
        <section>
            <h2 class="text-3xl mb-4">Participants</h2>

            {% if can_be_changed %}
                <form method="POST">
                    {% csrf_token %}
                    {{ form.management_form }}

                    <div class="grid grid-cols-1 md:grid-cols-participants-edit gap-2 mb-8">
                        <div class="w-auto md:block hidden"></div>
                        <div class="hidden md:block font-bold">Full name</div>
                        <div class="hidden md:block font-bold">Birth year</div>
                        <div class="hidden md:block font-bold">Graduation year</div>
                        <div class="hidden md:block font-bold text-center">Delete?</div>

                        {% for f in form %}
                        <div class="w-auto whitespace-nowrap text-xl {% if f.field.required %}font-bold{% endif %} mt-4 md:py-3 md:mt-0 md:text-base">
                            Participant {{ forloop.counter }}
                            {{ f.id }}
                        </div>
                        <div>
                            <label class="md:hidden font-bold {% if f.full_name.errors %}text-red-600{% endif %}" for="id_{{ f.full_name.html_name }}">Full name:</label>
                            {% bfield f.full_name %}
                        </div>
                        <div>
                            <label class="md:hidden font-bold {% if f.birth_year.errors %}text-red-600{% endif %}" for="id_{{ f.birth_year.html_name }}">Birth year:</label>
                            {% bfield f.birth_year %}
                        </div>
                        <div>
                            <label class="md:hidden font-bold {% if f.graduation_year.errors %}text-red-600{% endif %}" for="id_{{ f.graduation_year.html_name }}">Graduation year:</label>
                            {% bfield f.graduation_year %}
                        </div>
                        <div class="flex md:justify-center items-center gap-2">
                            {% bcheckbox f.DELETE %}
                            <label class="md:hidden font-bold" for="id_{{ f.DELETE.html_name }}">Delete?</label>
                        </div>
                        {% endfor %}
                    </div>

                    <button type="submit" class="btn">Update</button>
                </form>
            {% else %}
                <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
                {% for f in form %}
                    <div>
                        <h3 class="text-xl mt-3 mb-1">
                            Participant {{ forloop.counter }}
                            {{ f.id }}
                        </h3>
                        <p>
                            <strong>Name:</strong>
                            {{ f.full_name.value|stringformat:'s' }}
                        </p>
                        <p>
                            <strong>Birth year:</strong>
                            {{ f.birth_year.value|stringformat:'s' }}
                        </p>
                        <p>
                            <strong>Graduation year:</strong>
                            {{ f.graduation_year.value|stringformat:'s' }}
                        </p>
                    </div>
                {% endfor %}
                </div>
            {% endif %}
        </section>
    </main>
{% endblock %}