bullet/bullet/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

bullet/bullet_admin/urls.py
from bullet_admin.views import (
    CompetitionSwitchView,
    albums,
    archive,
    auth,
    category,
    categoryproblems,
    competition,
    content,
    documents,
    education,
    emails,
    home,
    results,
    scanning,
    teams,
    users,
    venues,
)
from django.urls import path

app_name = "badmin"
urlpatterns = [
    path("", home.HomeView.as_view(), name="home"),
    path("release_notes/", home.ReleaseNotesView.as_view(), name="release_notes"),
    path("auth/login/", auth.LoginView.as_view(), name="login"),
    path("auth/logout/", auth.LogoutView.as_view(), name="logout"),
    path(
        "auth/password_change/",
        auth.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "auth/password_reset/",
        auth.PasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "auth/password_reset/<uidb64>/<token>/",
        auth.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path("competitions/", CompetitionSwitchView.as_view(), name="competition_switch"),
    path(
        "competitions/edit/",
        competition.CompetitionUpdateView.as_view(),
        name="competition_edit",
    ),
    path(
        "competitions/new/",
        competition.CompetitionCreateView.as_view(),
        name="competition_create",
    ),
    path(
        "competitions/finalize/",
        competition.CompetitionFinalizeView.as_view(),
        name="competition_finalize",
    ),
    path("categories/", category.CategoryListView.as_view(), name="category_list"),
    path(
        "categories/new", category.CategoryCreateView.as_view(), name="category_create"
    ),
    path(
        "categories/<pk>", category.CategoryUpdateView.as_view(), name="category_edit"
    ),
    path("content/pages/", content.PageListView.as_view(), name="page_list"),
    path("content/pages/new/", content.PageCreateView.as_view(), name="page_create"),
    path("content/pages/<pk>/", content.PageEditView.as_view(), name="page_edit"),
    path(
        "content/pages/<pk>/delete/",
        content.PageDeleteView.as_view(),
        name="page_delete",
    ),
    path(
        "content/blocks/",
        content.ContentBlockListView.as_view(),
        name="contentblock_list",
    ),
    path(
        "content/blocks/trans/<group>/<reference>/",
        content.ContentBlockTranslationListView.as_view(),
        name="contentblock_trans",
    ),
    path(
        "content/blocks/new/",
        content.ContentBlockCreateView.as_view(),
        name="contentblock_create",
    ),
    path(
        "content/blocks/edit/<pk>/",
        content.ContentBlockEditView.as_view(),
        name="contentblock_edit",
    ),
    path(
        "content/blocks/delete/<pk>/",
        content.ContentBlockDeleteView.as_view(),
        name="contentblock_delete",
    ),
    path(
        "content/logos/",
        content.LogoListView.as_view(),
        name="logo_list",
    ),
    path(
        "content/logos/edit/<pk>/",
        content.LogoEditView.as_view(),
        name="logo_edit",
    ),
    path(
        "content/logos/create/",
        content.LogoCreateView.as_view(),
        name="logo_create",
    ),
    path(
        "content/logos/delete/<pk>/",
        content.LogoDeleteView.as_view(),
        name="logo_delete",
    ),
    path(
        "content/menu/",
        content.MenuItemListView.as_view(),
        name="menu_list",
    ),
    path(
        "content/menu/edit/<pk>/",
        content.MenuItemEditView.as_view(),
        name="menu_edit",
    ),
    path(
        "content/menu/delete/<pk>/",
        content.MenuItemDeleteView.as_view(),
        name="menu_delete",
    ),
    path(
        "content/menu/create/",
        content.MenuItemCreateView.as_view(),
        name="menu_create",
    ),
    path("teams/", teams.TeamListView.as_view(), name="team_list"),
    path(
        "teams/assign_numbers/",
        teams.AssignTeamNumbersView.as_view(),
        name="team_assign_numbers",
    ),
    path("teams/export/", teams.TeamExportView.as_view(), name="team_export"),
    path("teams/<int:pk>/", teams.TeamEditView.as_view(), name="team_edit"),
    path(
        "teams/<int:pk>/to_competition/",
        teams.TeamToCompetitionView.as_view(),
        name="team_to_competition",
    ),
    path(
        "teams/<int:pk>/resend_confirmation/",
        teams.TeamResendConfirmationView.as_view(),
        name="team_resend_confirmation",
    ),
    path(
        "teams/<int:pk>/delete/",
        teams.TeamDeleteView.as_view(),
        name="team_delete",
    ),
    path("teams/waiting/", teams.WaitingListView.as_view(), name="waiting_list"),
    path(
        "teams/waiting/automove/",
        teams.WaitingAutomoveView.as_view(),
        name="waiting_automove",
    ),
    path("_school_input", teams.SchoolInputView.as_view(), name="school_input"),
    path("users/", users.UserListView.as_view(), name="user_list"),
    path("users/create/", users.UserCreateView.as_view(), name="user_create"),
    path("users/<int:pk>/", users.UserEditView.as_view(), name="user_edit"),
    path(
        "scanning/problems/",
        scanning.ProblemScanView.as_view(),
        name="scanning_problems",
    ),
    path(
        "scanning/problems/undo/",
        scanning.UndoScanView.as_view(),
        name="scanning_problems_undo",
    ),
    path(
        "scanning/review/",
        scanning.VenueReviewView.as_view(),
        name="scanning_review",
    ),
    path(
        "scanning/review/<int:pk>/",
        scanning.TeamReviewView.as_view(),
        name="scanning_review_team",
    ),
    path(
        "scanning/review/<int:pk>/toggle/",
        scanning.TeamToggleReviewedView.as_view(),
        name="scanning_review_toggle_team",
    ),
    path("scanning/problems/api/", scanning.ApiProblemSolveView.as_view()),
    path("emails/", emails.CampaignListView.as_view(), name="email_list"),
    path("emails/create/", emails.CampaignCreateView.as_view(), name="email_create"),
    path(
        "emails/<int:pk>/edit/", emails.CampaignUpdateView.as_view(), name="email_edit"
    ),
    path("emails/<int:pk>/", emails.CampaignDetailView.as_view(), name="email_detail"),
    path(
        "emails/<int:pk>/teams/",
        emails.CampaignTeamListView.as_view(),
        name="email_teams",
    ),
    path(
        "emails/<int:pk>/test/",
        emails.CampaignSendTestView.as_view(),
        name="email_test",
    ),
    path(
        "emails/<int:pk>/send/",
        emails.CampaignSendView.as_view(),
        name="email_send",
    ),
    path(
        "documents/certificates/",
        documents.CertificateView.as_view(),
        name="docs_certificates",
    ),
    path(
        "documents/team_lists/",
        documents.TeamListView.as_view(),
        name="docs_teamlists",
    ),
    path("results/", results.ResultsHomeView.as_view(), name="results"),
    path(
        "results/announce/<venue>/",
        results.ResultsAnnouncementView.as_view(),
        name="results_announce",
    ),
    path("venues/", venues.VenueListView.as_view(), name="venue_list"),
    path("venues/<int:pk>/", venues.VenueUpdateView.as_view(), name="venue_update"),
    path("venues/create/", venues.VenueCreateView.as_view(), name="venue_create"),
    path("education/schools/", education.SchoolListView.as_view(), name="school_list"),
    path(
        "education/schools/<int:pk>/",
        education.SchoolUpdateView.as_view(),
        name="school_update",
    ),
    path(
        "education/schools/create/",
        education.SchoolCreateView.as_view(),
        name="school_create",
    ),
    path(
        "problems/generate/",
        categoryproblems.ProblemsGenerateView.as_view(),
        name="problems_generate",
    ),
    path("gallery/albums/", albums.AlbumListView.as_view(), name="album_list"),
    path("gallery/albums/new/", albums.AlbumCreateView.as_view(), name="album_create"),
    path(
        "gallery/albums/<int:pk>/", albums.AlbumUpdateView.as_view(), name="album_edit"
    ),
    path(
        "archive/import/",
        archive.ProblemImportView.as_view(),
        name="archive_import",
    ),
]

bullet/web/urls.py
from countries.views import CountryDetectView, CountrySelectView
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path, re_path

from web import views
from web.views import page

urlpatterns = [
    path("", CountryDetectView.as_view(), name="root"),
    path("country_selector/", CountrySelectView.as_view(), name="country_selector"),
    path("admin/", include("bullet_admin.urls")),
    re_path(
        r"^(?P<b_country>[a-z]{2})/(?P<b_language>[a-z\-]+)/",
        include(
            [
                path("", page.PageView.as_view(), name="homepage"),
                path("", include("competitions.urls")),
                path("", include("problems.urls")),
                path("", include("gallery.urls")),
                path("admin/", views.AdminRedirectView.as_view()),
                path("<slug>/", page.PageView.as_view(), name="page"),
            ]
        ),
    ),
]

handler404 = "web.views.error_404_view"

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns.append(
    re_path(
        r"^(?!([a-z]{2})/([a-z\-]+)/).*/", CountryDetectView.as_view(), name="redirect"
    )
)

bullet/bullet_admin/views/album.py
from countries.logic.detection import get_country_language_from_request
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.utils.functional import cached_property
from django.views.generic import CreateView, DeleteView, FormView, ListView, UpdateView
from gallery.models import Album, Photo

from bullet_admin.access import PermissionCheckMixin, is_admin
from bullet_admin.forms.album import AlbumForm, AlbumUploadForm
from bullet_admin.mixins import RedirectBackMixin
from bullet_admin.utils import get_active_competition
from bullet_admin.views import GenericDeleteView, GenericForm
from bullet_admin.views.generic.links import (
    DeleteIcon,
    EditIcon,
    ExternalViewIcon,
    Link,
    NewLink,
)
from bullet_admin.views.generic.list import GenericList


class AlbumListView(PermissionCheckMixin, GenericList, ListView):
    required_permissions = [is_admin]
    list_links = [
        NewLink("album", reverse_lazy("badmin:album_create")),
    ]

    table_labels = {"slug": "URL suffix"}
    table_fields = ["title", "slug", "country"]
    table_field_templates = {
        "country": "bullet_admin/partials/field__country.html",
    }

    def get_queryset(self):
        return Album.objects.filter(competition=get_active_competition(self.request))

    def get_row_links(self, obj) -> list[Link]:
        assert self.detection
        view = reverse(
            "archive_album",
            kwargs={
                "b_country": self.detection[0],
                "b_language": self.detection[1],
                "competition_number": obj.competition.number,
                "slug": obj.slug,
            },
        )

        return [
            Link(
                "blue",
                "mdi:image-outline",
                "Photos",
                reverse("badmin:album_photo_list", args=[obj.pk]),
            ),
            EditIcon(reverse("badmin:album_update", args=[obj.pk])),
            ExternalViewIcon(view),
            DeleteIcon(reverse("badmin:album_delete", args=[obj.pk])),
        ]

    def dispatch(self, request, *args, **kwargs):
        self.detection = get_country_language_from_request(self.request)
        if not self.detection:
            return redirect("country_selector")

        return super().dispatch(request, *args, **kwargs)


class AlbumFormMixin(GenericForm):
    form_class = AlbumForm

    def get_form_kwargs(self):
        kw = super().get_form_kwargs()
        kw["competition"] = get_active_competition(self.request)
        return kw


class AlbumUpdateView(
    PermissionCheckMixin, AlbumFormMixin, RedirectBackMixin, UpdateView
):
    required_permissions = [is_admin]
    form_title = "Edit album"

    def get_default_success_url(self):
        return reverse("badmin:album_update", kwargs={"pk": self.object.id})

    def get_queryset(self):
        return Album.objects.filter(competition__branch=self.request.BRANCH)  # type:ignore

    def form_valid(self, form):
        ret = super().form_valid(form)
        messages.success(self.request, "Album edited successfully.")
        return ret


class AlbumCreateView(PermissionCheckMixin, AlbumFormMixin, CreateView):
    required_permissions = [is_admin]
    form_title = "New album"

    def get_success_url(self):
        return reverse("badmin:album_photo_list", kwargs={"pk": self.object.id})

    def form_valid(self, form):
        ret = super().form_valid(form)
        messages.success(self.request, "Album created successfully.")
        return ret


class AlbumDeleteView(PermissionCheckMixin, RedirectBackMixin, GenericDeleteView):
    required_permissions = [is_admin]
    model = Album
    default_success_url = reverse_lazy("badmin:album_list")

    def form_valid(self, form):
        super().form_valid(form)
        messages.success(self.request, "Album deleted successfully.")
        return HttpResponseRedirect(self.get_success_url())


class AlbumPhotoListView(PermissionCheckMixin, GenericList, ListView):
    required_permissions = [is_admin]
    table_fields = ["image"]
    table_field_templates = {"image": "bullet_admin/albums/field__image.html"}

    def get_list_title(self):
        return f"Photos in {self.album.title}"

    def get_list_links(self) -> list[Link]:
        return [
            Link(
                "green",
                "mdi:upload",
                "Upload photos",
                reverse("badmin:album_upload", args=[self.album.id]),
            )
        ]

    def get_row_links(self, obj) -> list[Link]:
        return [
            DeleteIcon(
                reverse("badmin:album_photo_delete", args=[self.album.id, obj.id])
            )
        ]

    @cached_property
    def album(self):
        return get_object_or_404(Album, id=self.kwargs["pk"])

    def get_queryset(self):
        return Photo.objects.filter(album=self.album)


class AlbumPhotoDeleteView(PermissionCheckMixin, GenericDeleteView, DeleteView):
    required_permissions = [is_admin]

    @cached_property
    def album(self):
        return get_object_or_404(Album, id=self.kwargs["album_pk"])

    def get_queryset(self):
        return Photo.objects.filter(album=self.album)

    def get_success_url(self):
        return reverse("badmin:album_photo_list", kwargs={"pk": self.album.id})


class AlbumUploadView(PermissionCheckMixin, GenericForm, FormView):
    required_permissions = [is_admin]
    form_class = AlbumUploadForm
    form_title = "Upload photos"
    form_multipart = True
    form_submit_label = "Upload"
    form_submit_icon = "mdi:upload"

    def get_success_url(self):
        return reverse("badmin:album_photo_list", kwargs={"pk": self.album.id})

    @cached_property
    def album(self):
        return get_object_or_404(Album, id=self.kwargs["pk"])

    def form_valid(self, form):
        for file in form.cleaned_data["photo_files"]:
            photo = Photo(album=self.album, image=file)
            photo.read_taken_at()
            photo.save()

        messages.success(self.request, "Photos uploaded successfully.")
        return HttpResponseRedirect(self.get_success_url())

bullet/bullet_admin/views/archive.py
from django.contrib import messages
from django.shortcuts import redirect
from django.views.generic import FormView
from problems.logic.upload import ProblemImportError

from bullet_admin.access import (
    PermissionCheckMixin,
    is_branch_admin,
    is_country_admin,
)
from bullet_admin.forms.archive import ProblemImportForm, ProblemUploadForm
from bullet_admin.utils import get_active_competition
from bullet_admin.views import GenericForm


class ProblemImportView(PermissionCheckMixin, GenericForm, FormView):
    required_permissions = [is_branch_admin]
    form_class = ProblemImportForm
    template_name = "bullet_admin/archive/import.html"

    def get_form_kwargs(self):
        kw = super().get_form_kwargs()
        kw["competition"] = get_active_competition(self.request)
        return kw

    def form_valid(self, form):
        try:
            form.save()
            messages.success(self.request, "Successfully imported problems.")
        except ProblemImportError as e:
            messages.error(self.request, str(e))
        return redirect("badmin:archive_import")


class ProblemPDFUploadView(PermissionCheckMixin, GenericForm, FormView):
    required_permissions = [is_country_admin]
    form_class = ProblemUploadForm
    form_title = "Upload problems"
    form_multipart = True

    def get_form_kwargs(self):
        kw = super().get_form_kwargs()
        kw["competition"] = get_active_competition(self.request)
        return kw

    def form_valid(self, form):
        form.save()
        messages.success(self.request, "Successfully uploaded problems.")
        return redirect("badmin:archive_problem_upload")

bullet/bullet_admin/templates/bullet_admin/home/dates.html
{% load access %}
<div class="border-b border-gray-200 pb-4">
    <h2 class="text-base font-semibold text-gray-900">
        Important dates
        <span class="text-gray-700 text-sm font-normal">(UTC)</span>
    </h2>
</div>
<dl class="divide-y divide-gray-100">
    <div class="px-3 py-4 sm:grid sm:grid-cols-2 sm:gap-4 sm:px-0">
        <dt class="text-sm font-medium text-gray-900">Web start</dt>
        <dd class="mt-1 text-sm text-gray-700 sm:mt-0 flex items-center tabular-nums">
            {{ competition.web_start|date:"d.m.Y H:i" }}
            {% if competition.state > competition.state.BEFORE_WEB_START %}
                <b-icon class="text-green-600 w-4 h-4 ml-1"
                      icon="mdi:check"></b-icon>
            {% endif %}
        </dd>
    </div>
    <div class="px-3 py-4 sm:grid sm:grid-cols-2 sm:gap-4 sm:px-0">
        <dt class="text-sm font-medium text-gray-900">Registration start</dt>
        <dd class="mt-1 text-sm text-gray-700 sm:mt-0 flex items-center tabular-nums">
            {{ competition.registration_start|date:"d.m.Y H:i" }}
            {% if competition.state > competition.state.BEFORE_REGISTRATION %}
                <b-icon class="text-green-600 w-4 h-4 ml-1"
                      icon="mdi:check"></b-icon>
            {% endif %}
        </dd>
    </div>
    <div class="px-3 py-4 sm:grid sm:grid-cols-2 sm:gap-4 sm:px-0">
        <dt class="text-sm font-medium text-gray-900">Registration end</dt>
        <dd class="mt-1 text-sm text-gray-700 sm:mt-0 flex items-center tabular-nums">
            {{ competition.registration_end|date:"d.m.Y H:i" }}
            {% if competition.state > competition.state.REGISTRATION %}
                <b-icon class="text-green-600 w-4 h-4 ml-1"
                      icon="mdi:check"></b-icon>
            {% endif %}
        </dd>
    </div>
    <div class="px-3 py-4 sm:grid sm:grid-cols-2 sm:gap-4 sm:px-0">
        <dt class="text-sm font-medium text-gray-900">Competition start</dt>
        <dd class="mt-1 text-sm text-gray-700 sm:mt-0 flex items-center tabular-nums">
            {{ competition.competition_start|date:"d.m.Y H:i" }}
            {% if competition.state >= competition.state.COMPETITION %}
                <b-icon class="text-green-600 w-4 h-4 ml-1"
                      icon="mdi:check"></b-icon>
            {% endif %}
        </dd>
    </div>
</dl>
{% is_branch_admin as can_edit %}
{% if can_edit %}
    <div class="mt-2">
        {% url "badmin:competition_edit" as edit_url %}
        {% #abtn url=edit_url label="Competition settings" icon="mdi:cog" %}
    </div>
{% endif %}

bullet/bullet_admin/templates/bullet_admin/home/help.html
<div class="border-b border-gray-200 pb-4">
    <h2 class="text-base font-semibold text-gray-900">Help & updates</h2>
</div>
<p class="mt-4 text-gray-700 text-sm">
    If you have problems, difficulties, questions, or ideas for improvement, please contact us:
    <a href="mailto:naboj-it@trojsten.sk"
       class="link-primary">naboj-it@trojsten.sk</a>
</p>
<p class="mt-4 text-gray-700 text-sm">
    Running Náboj system (Bullet) version <span class="font-semibold">{{ bullet_version }}</span>.
</p>
<div class="mt-4">
    {% url "badmin:release_notes" as notes_url %}
    {% #abtn url=notes_url label="Release notes" icon="mdi:newspaper" %}
</div>

bullet/bullet_admin/templates/bullet_admin/home/main.html
{% extends "bullet_admin/base.html" %}
{% load badmin countries %}
{% block title %}
    Dashboard
{% endblock title %}

{% block content %}
    <div class="p-8">
        {% aheader show_subtitle=True %}
            {% slot title %}
                {% if user.first_name %}
                    👋 Hi, {{ user.first_name }}!
                {% else %}
                    👋 Hi!
                {% endif %}
            {% endslot %}
            Welcome to the Náboj administration system. This is your dashboard, where you can easily find information and access common actions.
        {% endaheader %}
        <div class="grid grid-cols-1 sm:grid-cols-3 gap-6">
            <div>{% include "./state.html" %}</div>
            <div>{% include "./dates.html" %}</div>
            <div>{% include "./help.html" %}</div>
        </div>
        <div class="mt-4 grid grid-cols-1 gap-4 sm:grid-cols-2">
            {% regroup venues by country as venues_by_country %}
            {% for country, venues in venues_by_country %}
                <div class="font-semibold p-3 border-b border-gray-200 sm:col-span-2">
                    {% get_country country as country_info %}
                    {% #country name=country_info.name code=country_info.code %}
                </div>
                {% for v in venues %}
                    <a href="{% url "badmin:venue_detail" v.id %}">
                        <div class="bg-gray-100 border border-gray-200 rounded-md p-3">
                            <div class="font-semibold">{{ v }}</div>
                            {% if competition.state >= competition.state.REGISTRATION %}
                                <div class="rounded bg-white w-full h-2 overflow-hidden my-1">
                                    <div class="h-full bg-green-600"
                                         style="width: {% percent v.competing v.capacity %}%">
                                    </div>
                                </div>
                            {% endif %}
                            <div class="text-sm text-gray-800">
                                {% if competition.state < competition.state.REGISTRATION %}
                                    {{ v.capacity }} teams capacity
                                {% else %}
                                    {{ v.competing }} / {{ v.capacity }} teams registered
                                    {% if v.waiting %}(+ {{ v.waiting }} on the waiting list){% endif %}
                                {% endif %}
                            </div>
                            {% if competition.state >= competition.state.AFTER_REGISTRATION %}
                                {% if competition.state < competition.state.AFTER_COMPETITION %}
                                    <div class="rounded bg-white w-full h-2 overflow-hidden mb-1 mt-3">
                                        <div class="h-full bg-purple-600"
                                             style="width: {% percent v.checked_in v.competing %}%">
                                        </div>
                                    </div>
                                    <div class="text-sm text-gray-800">
                                        {{ v.checked_in }} / {{ v.competing }} teams checked in
                                    </div>
                                {% else %}
                                    <div class="rounded bg-white w-full h-2 overflow-hidden mb-1 mt-3">
                                        <div class="h-full bg-blue-600"
                                             style="width: {% percent v.reviewed v.competing %}%">
                                        </div>
                                    </div>
                                    <div class="text-sm text-gray-800">
                                        {{ v.reviewed }} / {{ v.competing }} teams reviewed
                                    </div>
                                {% endif %}
                            {% endif %}
                        </div>
                    </a>
                {% endfor %}
            {% endfor %}
        </div>
    </div>
{% endblock content %}

bullet/bullet_admin/templates/bullet_admin/home/release_notes.html
{% extends "bullet_admin/base.html" %}
{% load markdownify %}
{% block title %}
    Release notes
{% endblock title %}

{% block content %}
    <div class="p-8 prose mx-auto">{{ changelog|markdownify }}</div>
{% endblock content %}

bullet/bullet_admin/templates/bullet_admin/home/state.html
<div class="border-b border-gray-200 pb-4">
    <h2 class="text-base font-semibold text-gray-900">Current state</h2>
</div>
<div class="pt-4">
    <div class="text-3xl text-gray-700">{{ competition.state.label }}</div>
    <p class="text-gray-700 mt-1 leading-6">
        {% if competition.state == competition.state.BEFORE_WEB_START %}
            The competition is not visible to the public.
        {% elif competition.state == competition.state.BEFORE_REGISTRATION %}
            We are waiting for the registration to start.
        {% elif competition.state == competition.state.REGISTRATION %}
            The registration is open.
        {% elif competition.state == competition.state.AFTER_REGISTRATION %}
            The registration is now closed.
        {% elif competition.state == competition.state.COMPETITION %}
            The competition has begun and is currently underway.
        {% elif competition.state == competition.state.AFTER_COMPETITION %}
            The competition is over, but the results haven't been announced yet.
        {% elif competition.state == competition.state.LOCKED %}
            The competition is over, and no further changes are allowed.
        {% endif %}
    </p>
</div>